


spring:
  datasource:
    name: cnpc_local_k40  #数据库名
    url: jdbc:mysql://10.112.181.70:3306/cnpc_local_k40?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false  #url
    username: root  #用户名
    password: bupt  #密码
    driver-class-name: com.mysql.cj.jdbc.Driver  #数据库链接驱动


mybatis:
  mapper-locations: classpath:mapper/*.xml  #配置映射文件
  type-aliases-package: com.cnpc.analysis.bean #配置实体类